version: '3.8'

services:
  odoo-invoice-monitor:
    build: .
    container_name: odoo-invoice-monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 