version: '3.8'

services:
  odoo-invoice-monitor:
    build: .
    container_name: odoo-invoice-monitor
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 